Add encryption for backup
shakapark/Backup-Tool pull request #16
Opened 2023-09-05 15:16 UTC by Bizyroth

2023-09-14 10:57 UTC, shakapark requested changes

2023-09-14 10:57 UTC, shakapark commented on Dockerfile
> +ENV ENCRYPTION_ENABLE=true
Can you disable it by default ?

2023-09-14 10:57 UTC, shakapark commented on backupToAWS.sh
> +  if [ "$ENCRYPTION_ENABLE" = "true" ]; then
Can you add encryption option with $ENCRYPTION variable, like $COMPRESSION for all backup and restore ?

2023-09-14 12:19 UTC, Bizyroth commented on Dockerfile
> +ENV ENCRYPTION_ENABLE=true
Done

2023-09-14 12:19 UTC, Bizyroth commented on backupToAWS.sh
> +  if [ "$ENCRYPTION_ENABLE" = "true" ]; then
Done

2023-09-14 12:46 UTC, shakapark commented on backupToAWS.sh
> +  if [ "$ENCRYPTION_ENABLE" = "true" ]; then
If you write ENCRYPTION=$( _command_ ): the value of ENCRYPTION will be the result of _command_. It must be the command itself

2023-10-13 12:57 UTC, shakapark approved these changes

2023-10-13 12:57 UTC, merged